language: cpp
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - gcc-7
      - g++-7
      - ninja-build
      - clang-6.0
      - libmpfr-dev
      - libgmp3-dev
      - libeigen3-dev
      - libtbb-dev
      - libcgal-dev
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0

env:
  global:
   - BOOST_VERSION=1.66.0
  matrix:
    - TESTS=true

cache:
  apt:
  ccache: true
  directories:
    - ${TRAVIS_BUILD_DIR}/boost-${BOOST_VERSION}

os:
  - linux

compiler:
  - gcc

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
      if [[ "${BOOST_VERSION}" != "" ]]; then
        export BOOST_DIR=${TRAVIS_BUILD_DIR}/boost-${BOOST_VERSION}
        export BOOST_URL="https://github.com/boostorg/boost/archive/boost-${BOOST_VERSION}.tar.gz"
        mkdir -p ${BOOST_DIR}
        { travis_retry wget -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; } || exit 1
        CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"
      fi
      INCLUDE_DIR="/usr/include/"
    fi
  - cmake --version
  - if [[ "$CXX" = "g++" ]]; then export CXX="g++-7" CC="gcc-7"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "clang++" ]]; then export
   CXX="clang++-6.0" CC="clang-6.0"; fi
  - echo $CXX $CC
  # Install CGAL from source for Linux
  - cd $TRAVIS_BUILD_DIR
  - travis_retry curl -L -o CGAL-4.11.1.tar.gz https://github.com/CGAL/cgal/archive/releases/CGAL-4.11.1.tar.gz
  - tar zxvf CGAL-4.11.1.tar.gz &> install.log
  - cd cgal-releases-CGAL-4.11.1
  - CMAKE_OPTIONS+=" -DCMAKE_BUILD_TYPE=Release -DWITH_Eigen3=ON"
  - echo ${CMAKE_OPTIONS}
  - cmake ${CMAKE_OPTIONS} -G Ninja .
  - cmake --build .
  - sudo env "PATH=$PATH" cmake --build . --target install &> install.log
  - cd ..

before_script:
  - mkdir build
  - cd build

script:
  - echo $CXXFLAGS
  - echo $LDPATH
  - echo $PATH
  - echo $BOOST_DIR
  - CMAKE_OPTIONS="-DBOOST_ROOT=${BOOST_DIR} -DBUILD_SHARED_LIBS=ON"
  - echo CMAKE_OPTIONS
  - echo $CMAKE_OPTIONS
  - export CMAKE_OPTIONS="-DBOOST_ROOT=${BOOST_DIR} -DBUILD_SHARED_LIBS=ON"
  - echo $CMAKE_OPTIONS
  - ls -al /home/travis/build/iriberri/CDT-plusplus/boost-1.66.0
  - |
    if [[ ${TESTS} == "true" ]]; then
      CMAKE_OPTIONS+=" -DCMAKE_BUILD_TYPE=Debug -DTESTS:BOOL=ON"
    else
      CMAKE_OPTIONS+=" -DCMAKE_BUILD_TYPE=Release -DTESTS:BOOL=OFF"
    fi
  - echo $CMAKE_OPTIONS
  - cmake $CMAKE_OPTIONS -G Ninja ..
  - export CXXFLAGS=-I/home/travis/build/iriberri/CDT-plusplus/boost-1.66.0/include
  - export LDPATH=-L/home/travis/build/iriberri/CDT-plusplus/boost-1.66.0/lib
  - cmake --build .

